# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Medua-Management
version:      0.10
version_from: lib/Media/Management.pm
installdirs:  site
requires:
    Filter::Simple:                0.78
    Test::More:                    0.45
    Text::Tabs:                    98.112801

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
